preprocessy/preprocessy

evaluations/evaluate_correlation.ipynb
evaluations/evaluate_selectkbest.ipynb
preprocessy/feature_selection/_selectKBest.py
preprocessy/input/_read.py
preprocessy/scaling/_main.py

- Evaluated the performance of Correlation class on 4 common datasets
- Evaluated the performance of SelectKBest class on 100 randomly generated synthetic datasets of variable sizes and features.

Added evaluation scripts for feature selection classes

---

preprocessy/input/_read.py
tests/test_input.py

There are basically 2 types of errors that must be raised by the input module - 
1. File not found error
2. Incorrect file type error
I've refactored the code so that both the errors will now be caught. I've also updated the tests for them.

Fixed input build fail and test cases

---

preprocessy/input/_read.py
tests/test_input.py

1. validate_input function added in preprocessy/input/_read.py
-> so that non-string type values passed to file_name error can be caught 
2. test for the same is added in tests/test_input.py

Tests for input added

---

preprocessy/handlenullvalues/_main.py
tests/test_null.py

Solves Issue #43 
The files refractored are:
- handlenullvalues/_main.py
- test_null.py

Refractored Handle Null Values module

---

preprocessy/resampling/_split.py
tests/test_split.py

Solves Issue #43
The files refractored are:
- resampling/_split.py
- test_split.py

Refractored Resampling module

---

preprocessy/scaling/_main.py

This solves issue #43
Files changed are :
- preprocessy/scaling/_main.py

Refractored scaling module

---

preprocessy/scaling/_main.py
tests/test_scaling.py

Solves issue #26 and #42 
Files changed are : 
- scaling/_main.py
- tests/test_scaling.py

Tests added for Scaling module and tests parameterized

---

preprocessy/resampling/_split.py
requirements_dev.txt
tests/test_split.py

In addition to the issue #25 ,
- fixed name train_split to train_size
- fixed name test_split to test_size
fixes #25

solved target label null issue

---

preprocessy/outliers/_handleoutlier.py

Added input validation function in outliers module.
File changed :
- outliers/_handleoutlier.py

Added input validation function in outliers module

---

preprocessy/outliers/_handleoutlier.py
tests/test_outlier.py

Solves issue #26 and #42 
Added tests for outliers module
Files added :
- tests/test_outlier.py

Added tests for outliers module

---

tests/test_base.py
tests/test_config.py
tests/test_correlation.py
tests/test_encode.py
tests/test_input.py
tests/test_kfold.py
tests/test_null.py
tests/test_selectkbest.py
tests/test_split.py

This closes issue #42 
Files changed : 
- test_correlation.py
- test_encode.py
- test_input.py
- test_kfold.py
- test_null.py
- test_selectkbest.py
- test_split.py
- test_base.py
- test_config.py

Pytest parameterization

---

CHANGES.rst
LICENSE.rst
docs/api.rst
docs/changes.rst
docs/conf.py
docs/contributing.rst
docs/index.rst
docs/license.rst
preprocessy/resampling/_kfold.py
preprocessy/resampling/_split.py
preprocessy/scaling/_main.py

I added a few pages in the docs and also configured the theme a bit. I've also added `sphinx-autodoc` and documentation for Resampling module. Fixes to #73 and #28.
Files added - 
- `LICENSE.rst`
- `CONTRIBUTING.rst`
- `CHANGES.rst`
- `api.rst`
I also had to format the `rst` manually. We'll have to look for some formatter as well.

Added miscellaneous pages in docs

---

preprocessy/encoding/__init__.py
preprocessy/encoding/_categorical.py
preprocessy/input/__init__.py
preprocessy/input/_read.py
preprocessy/parse/__init__.py
preprocessy/parse/_summarize.py
preprocessy/pipelines/_base.py
preprocessy/pipelines/config.py
tests/test_base.py
tests/test_config.py
tests/test_encode.py
tests/test_input.py
tests/test_parse.py

Since almost all functions differentiate between categorical columns and regular columns, I added a new module after the Reader module to calculate the categorical columns and store their names in `params["cat_cols"]`
- Renamed `EncodeData` to `Encoder`
- Removed `DateTime` check until it can be fixed
- Updated condition to check for `int` or `str` column
- Renamed `ReadData` to `Reader`
- Refactored `Reader` to support `params`
- Removed dataframe summary functions
- Refactored base pipeline as a direct consequence of refactoring `Reader`
- Refactored `save_config` as a direct consequence of refactoring base pipeline
- Added tests for `Parser`
- Updated tests for base pipeline, config, `Encoder` and `Reader`

Added parser module

---

preprocessy/pipelines/_base.py
requirements.txt
setup.py

The package used for the progress bar doesn't support Jupyter Notebooks for now.

Added progress bar

---

docs/api.rst
preprocessy/handlenullvalues/_main.py
preprocessy/pipelines/_base.py
preprocessy/pipelines/_feature_selection_pipeline.py
preprocessy/pipelines/_standard_pipeline.py
preprocessy/scaling/_main.py

Docs:
* NullValueHandler
* BasePipeline
Fixes
* Mean/Median to be calculated column wise instead of entire dataframe while handling null values

Added docs for null values handler, scaler and pipelines

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
CHANGES.rst
CONTRIBUTING.md
docs/contributing.rst

Changes -
- Added templates for PR, Bug Report & Feature Request
- Updated `Contributing.rst`
- Updated `Changes.rst`

Documentation

---

docs/parameters.rst
preprocessy/resampling/_kfold.py
preprocessy/resampling/_split.py
tests/test_kfold.py

refactored kfold cross validation to support params

---

docs/parameters.rst
preprocessy/feature_selection/_selectKBest.py

updated score func docs

---

evaluations/evaluate_scaling.ipynb

Added scaling evaluations

---

README.md

Update README with latest links

---

.github/ISSUE_TEMPLATE/feature_request.md
docs/parameters.rst

Check the preview generated for verification of the changes
- Fixes #133

Updated parameters.rst to include additional information for parameters

---

README.md
docs/index.rst
docs/research.rst
pyproject.toml
requirements_docs.txt
setup.py

Added research paper section to docs

---

README.md

Fix broken link for license 

---

.flake8
.gitignore
preprocessy/encoding/_categorical.py
preprocessy/missing_data/_main.py
preprocessy/outliers/_handleoutlier.py
preprocessy/parse/_summarize.py
preprocessy/pipelines/_base.py
preprocessy/pipelines/config.py
preprocessy/scaling/_main.py

- Fixes Flake8 Errors
Checklist:

Code cleanup

---

requirements_dev.txt

- Fixes dependabot alert
Checklist:

Updated pytest version to remove security vulnerablity
